-- DB SCHEMA 생성
CREATE DATABASE testdb;

-- SCHEMA를 사용하도록 접속 수행
USE emsDB;

-- TABLE를 생성
CREATE TABLE tbl_bbs (
	BBS_ID	BIGINT PRIMARY KEY AUTO_INCREMENT,
	BBS_P_ID	BIGINT	DEFAULT 0,	
	BBS_WRITER	nVARCHAR(50)	NOT NULL,	
	BBS_DATE	VARCHAR(10),		
	BBS_TIME	VARCHAR(10),	
	BBS_SUBJECT	nVARCHAR(125),		
	BBS_CONTENT	nVARCHAR(1000),		
	BBS_COUNT	INT	DEFAULT 0	
);
DESC tbl_bbs ;
