USE emsDB;
DROP TABLE tbl_comment;
CREATE TABLE tbl_comment (
	CMT_ID	BIGINT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CMT_P_ID BIGINT	DEFAULT 0,	
	CMT_WRITER	VARCHAR(20)	NOT NULL,	
	CMT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ,		
	CMT_TEXT VARCHAR(400)		
);
SELECT * FROM tbl_comment ;