CREATE TABLE tbl_books (
    B_CODE	VARCHAR2(20),
    B_NAME	nVARCHAR2(125)	NOT NULL,	
    B_AUTHER	nVARCHAR2(125)	NOT NULL,	
    B_COMP	nVARCHAR2(125),		
    B_YEAR	VARCHAR2(10),		
    B_IPRICE	NUMBER,	
    CONSTRAINT PK_BOOK PRIMARY KEY (b_code)
);

CREATE TABLE tbl_read_book (
        RB_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
        RB_BCODE	VARCHAR2(20)	NOT NULL,	
        RB_DATE	VARCHAR2(10)	NOT NULL,	
        RB_STIME	VARCHAR2(10),		
        RB_RTIME	NUMBER(10,3),		
        RB_SUBJECT	nVARCHAR2(20),		
        RB_TEXT	nVARCHAR2(400),		
        RB_STAR	NUMBER,		
        CONSTRAINT FK_READ_BOOK FOREIGN KEY (RB_BCODE)
        REFERENCES TBL_BOOKS(B_CODE) ON DELETE CASCADE 
);


CREATE SEQUENCE SEQ_READ_BOOK
START WITH 1 INCREMENT BY 1;

SELECT * FROM tbl_books ;



